<<<<<<< HEAD
version: "3.8"

=======
version: '3.8'
>>>>>>> 80e293f (initial)
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:pass@db:5432/yourdb
    ports:
      - "8000:8000"

volumes:
  db_data:
