###########################
# render.yaml corrigé     #
###########################

services:
  - type: web
    name: backend
    runtime: docker
    region: frankfurt      # ← backend en Frankfort
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /docs
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pfe-db
          property: connectionString  # URL interne correcte  :contentReference[oaicite:1]{index=1}
      - key: PORT
        value: "8000"

databases:
  - name: pfe-db
    plan: free
    region: frankfurt      # ← **ajouté**
    databaseName: yourdb
    user: user
